version: '3.8'
services:
  genderdetector:
    image: abel_gen
    command: python3 train.py
    volumes:
      - /home/tr-abel/project/gender_detector:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

